### ISSUE TITLE
Firmware 4.1.12 - All IKEv2 tunnels die after ~3 hours

### ISSUE THREAD

**Issue by cmosetick** [invizbox/firmware#4]
Running Firmware 4.1.12, I started noticing that around ~2 hours and 50 minutes of device uptime, all IKEv2 tunnels die, for no apparent reason. Rebooting the entire device temporarily resolves, and restore the tunnels.

Alternatively, using the web admin gui, switching the tunnel to a different server endpoint, creates a new fresh connection and gives you another 3 hours.

After seeing this issue repeatedly now for several weeks, I decided that I should do a hard device reset after the firmware upgrade. I used the reset.txt file via USB method. (which has previously worked great with issues on different firmware version.)

However, with Firmware 4.1.12, the hard reset via USB method has proven to be useless.
All IKEv2 tunnels still die after around 3 hours.
Looking forward to a fix for this asap.

(But still more interested in official Wireguard support at this time.)

**Comment by VincentRiou** [comment]
We got things wrong on the initial release of 4.1.12 by trying to use the "make_before_break" setting in `/etc/strongswan.d/charon.conf`. Unfortunately, this is something that can't work with VTI (which we use) and leads to a broken tunnel each time there is a rekey.

This got patched within hours of the release and the 4.1.12 was re-released. We haven't seen this issue since the very early days. I'm going to close it for now.

The patch is here: https://github.com/invizbox/feed/blob/f134931edb773c47ccbee714140c26bceaba9ebf/feed/configuration-update-ib2/uci-defaults/18_base_files#L923

If it's still happening on your system, delete `/etc/strongswan.d/charon.conf` and restert strongswan. After that, drop us a line in support and we'll have a look with you.

**Note**: using the USB for resetting does the same thing as clicking reset in the System page of the Administration UI (which is simpler to use when you still have access to the UI).
